version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-app
hooks:
  AfterInstall:
    - location: start_containers.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_app.sh
      timeout: 300
      runas: root
