version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/node-app

hooks:
  AfterInstall:
    - location: docker-start.sh  # Script to start Docker containers
      timeout: 300
      runas: root

  ApplicationStart:
    - location: docker-deploy.sh  # Script to deploy Docker containers
      timeout: 300
      runas: root
