version: 0.2  

env:
  parameter_store:
    DOCKER_REGISTRY_USERNAME: /docker/username
    DOCKER_REGISTRY_PASSWORD: /docker/password
    DOCKER_REGISTRY_URL: /docker-registry/url

phases:
  pre_build:
    commands:
      - echo "Logging into Docker registry"
   #   - echo "Username: $DOCKER_REGISTRY_USERNAME"  # Be careful with this in production
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_REGISTRY_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/node-app:latest" .
      - echo "Pushing Docker image"
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/node-app:latest"

artifacts:
  files:
    - '**/*'  
  discard-paths: yes  
 
