version: 0.2

phases:
  pre_build:
    commands:
      

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t node-app:latest .

artifacts:
  files:
    - '**/*'  # Include all files, or you can specify particular files or directories
  base-directory: 'node-app'  # This ensures artifacts are gathered from the right directory
  discard-paths: yes  # You can set this to 'no' if you want to preserve the file paths in the S3 bucket
