version: 0.2  

env:
  parameter_store:
    DOCKER_REGISTRY_USERNAME: /docker/username
    DOCKER_REGISTRY_PASSWORD: /docker/password
    DOCKER_REGISTRY_URL: /docker-registry/url

phases:
  pre_build:
    commands:
      - echo "Logging into Docker registry"
      - sudo apt-get install docker.io -y
      - sudo systemctl start docker
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" -p "$DOCKER_REGISTRY_PASSWORD"

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t Sheheriyar99/node-app:latest .
      - echo "Pushing Docker image"
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/node-app:latest"

artifacts:
  files:
    - '**/*'  
  discard-paths: yes  
 
