version: 0.2  

env:
  parameter_store:
    DOCKER_REGISTRY_USERNAME: /docker/username
    DOCKER_REGISTRY_PASSWORD: /docker/password
    DOCKER_REGISTRY_URL: /docker-registry/url

phases:
  pre_build:
    commands:
    #  - echo "Logging into Docker registry"
     # - docker login -u "$DOCKER_REGISTRY_USERNAME" -p --password-stdin

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t node-app:latest .
      - echo "Pushing Docker image"
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/node-app:latest"

artifacts:
  files:
    - '**/*'  # Include all files, or you can specify particular files or directories
  discard-paths: yes  # You can set this to 'no' if you want to preserve the file paths in the S3 bucket
