version: 0.2

phases:
  pre_build:
    commands:
      - echo "Cloning the repository..."
      - git clone https://github.com/Sheheriyar99/node-todo-cicd
      - cd node-todo-cicd

  build:
    commands:
      - echo "Building and testing the Docker image..."
      - docker build -t node-app:latest .
      - echo "Build & Test completed successfully."

artifacts:
  files:
    - '**/*'
