version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y docker
      - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose

  pre_build:
    commands:
      - echo "Cloning the repository..."
      - git clone https://github.com/Sheheriyar99/node-todo-cicd
      - cd node-todo-cicd

  build:
    commands:
      - echo "Building and testing the Docker image..."
      - docker build -t node-app:latest .
      - echo "Build & Test completed successfully."

artifacts:
  files:
    - '**/*'
