version: 0.2  

env:
  parameter_store:
    DOCKER_RESGISTRY_USERNAME: /docker/username
    DOCKER_RESGISTRY_PASSWORD: /docker/password
    DOCKER_RESGISTRY_URL: /docker-registry/url

phases:
  pre_build:
    commands:
      

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t "$DOCKER_RESGISTRY_URL/$DOCKER_RESGISTRY_USERNAME/node-app:latest" .
      - docker login -u "$RESGISTRY_USERNAME" -p "$DOCKER_RESGISTRY_PASSWORD"
      - docker push "$DOCKER_RESGISTRY_URL/$DOCKER_RESGISTRY_USERNAME/node-app:latest" 

artifacts:
  files:
    - '**/*'  # Include all files, or you can specify particular files or directories
  discard-paths: yes  # You can set this to 'no' if you want to preserve the file paths in the S3 bucket
